name: Helm Lint

on:
  workflow_call:

jobs:
  helm-lint:
    uses: kupecloud/github-workflows/.github/workflows/helm-lint.yaml@5f8c2a0126ce233053c56c04ca9a4d50f7f879b7
    with:
      chart-path: chart/hello-kupe
      lint-args: --set tenant=example-tenant
