name: Helm Lint

on:
  workflow_call:

jobs:
  helm-lint:
    uses: kupecloud/github-workflows/.github/workflows/helm-lint.yaml@56a9721ea10187892bc76c3c8885225990de8323 # v1.13.0
    with:
      chart-path: chart
      lint-args: --set tenant=example-tenant
