name: Lint

on:
  pull_request:
    branches:
      - main
    paths:
      - "go.mod"
      - "**.go"
      - ".github/workflows/lint.yaml"
      - "Makefile"
  workflow_call:

jobs:
  lint:
    uses: kupecloud/github-workflows/.github/workflows/go-lint.yaml@530d751e117f3a8451429d49e532a6df70b74432
