name: PR

on:
  pull_request:
    branches:
      - main
    paths:
      - "go.mod"
      - "go.sum"
      - "**.go"
      - "Dockerfile"
      - "chart/**"
      - ".github/workflows/**"
      - "Makefile"

permissions:
  contents: read

jobs:
  go-lint:
    name: Go Lint
    uses: ./.github/workflows/go-lint.yaml

  action-lint:
    name: Action Lint
    uses: ./.github/workflows/action-lint.yaml

  helm-lint:
    name: Helm Lint
    uses: ./.github/workflows/helm-lint.yaml

  rbac-audit:
    name: RBAC Secrets Audit
    uses: kupecloud/github-workflows/.github/workflows/helm-rbac-audit.yaml@98b8368020991c33bf4041bee6081d865ff4850a # v2.4.0
    with:
      chart-path: chart
      template-args: --set tenant=example-tenant --set cluster=example
      release-name: hello-kupe

  automount-audit:
    name: Pod Automount Audit
    uses: kupecloud/github-workflows/.github/workflows/helm-automount-audit.yaml@98b8368020991c33bf4041bee6081d865ff4850a # v2.4.0
    with:
      chart-path: chart
      template-args: --set tenant=example-tenant --set cluster=example
      release-name: hello-kupe

  unit-tests:
    name: Unit Tests
    needs:
      - go-lint
      - action-lint
      - helm-lint
    uses: ./.github/workflows/unit-tests.yaml
