name: Publish Image

on:
  workflow_call:
    inputs:
      version:
        description: Semantic release version without the leading v
        required: true
        type: string

permissions:
  contents: read
  packages: write
  id-token: write # Required for cosign keyless signing

jobs:
  publish:
    uses: kupecloud/github-workflows/.github/workflows/publish-image.yaml@56a9721ea10187892bc76c3c8885225990de8323 # v1.13.0
    with:
      version: ${{ inputs.version }}
    secrets: inherit
