name: Publish Image

on:
  workflow_call:
    inputs:
      version:
        description: Semantic release version without the leading v
        required: true
        type: string

permissions:
  contents: read
  packages: write
  id-token: write # Required for cosign keyless signing

jobs:
  publish:
    uses: kupecloud/github-workflows/.github/workflows/publish-image.yaml@5f8c2a0126ce233053c56c04ca9a4d50f7f879b7
    with:
      version: ${{ inputs.version }}
    secrets: inherit
