name: Publish Image

on:
  workflow_call:
    inputs:
      version:
        description: Semantic release version without the leading v
        required: true
        type: string

permissions:
  contents: read
  packages: write
  id-token: write # Required for cosign keyless signing

jobs:
  publish:
    uses: kupecloud/github-workflows/.github/workflows/publish-image.yaml@689a05f5764fb1960bb7e127b27987acc9129dd4 # v1.12.1
    with:
      version: ${{ inputs.version }}
    secrets: inherit
